version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '8080:80'
      - '81:81'
      - '443:443'
    environment:
      DEFAULT_HOST: jussmor.lan
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      - '/var/run/docker.sock:/tmp/docker.sock'